// <auto-generated />
using System;
using DemoHabitTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoHabitTracker.Migrations
{
    [DbContext(typeof(HabitTrackerDbContext))]
    partial class HabitTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoHabitTracker.Models.Activity", b =>
                {
                    b.Property<string>("Pkid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Tomato_richiesti")
                        .HasColumnType("int");

                    b.Property<string>("fkUsernName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fkparentActivity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pkid");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("DemoHabitTracker.Models.UserScore", b =>
                {
                    b.Property<string>("fkUserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("fkUserName");

                    b.ToTable("UserScores");
                });
#pragma warning restore 612, 618
        }
    }
}
